#!/usr/bin/env python3
from pathlib import Path

FILES = {'src/dada_4bar_synthesis/projection.py': '"""Projection-only inverse synthesis for a normalized '
                                          'four-bar loop."""\n'
                                          '\n'
                                          'from __future__ import annotations\n'
                                          '\n'
                                          'from dataclasses import asdict, dataclass\n'
                                          'import math\n'
                                          'from typing import Literal\n'
                                          '\n'
                                          'import numpy as np\n'
                                          'from scipy.optimize import differential_evolution\n'
                                          '\n'
                                          'OutputType = Literal["rocker", "coupler"]\n'
                                          '\n'
                                          '\n'
                                          '@dataclass(frozen=True, slots=True)\n'
                                          'class NormalizedFourBarGeometry:\n'
                                          '    """Scale-free four-bar geometry with crank radius '
                                          'fixed to one."""\n'
                                          '\n'
                                          '    ground_ratio: float\n'
                                          '    coupler_ratio: float\n'
                                          '    rocker_ratio: float\n'
                                          '    phase_rad: float = 0.0\n'
                                          '    assembly_branch: int = 1\n'
                                          '\n'
                                          '    def __post_init__(self) -> None:\n'
                                          '        for name, value in (\n'
                                          '            ("ground_ratio", self.ground_ratio),\n'
                                          '            ("coupler_ratio", self.coupler_ratio),\n'
                                          '            ("rocker_ratio", self.rocker_ratio),\n'
                                          '        ):\n'
                                          '            if not math.isfinite(value) or value <= '
                                          '0.0:\n'
                                          '                raise ValueError(f"{name} must be '
                                          'finite and positive.")\n'
                                          '        if not math.isfinite(self.phase_rad):\n'
                                          '            raise ValueError("phase_rad must be '
                                          'finite.")\n'
                                          '        if self.assembly_branch not in (-1, 1):\n'
                                          '            raise ValueError("assembly_branch must be '
                                          '-1 or 1.")\n'
                                          '\n'
                                          '    @property\n'
                                          '    def ground_pivot_angle_rad(self) -> float:\n'
                                          '        """Equivalent pivot angle when the shared crank '
                                          'phase is set to zero."""\n'
                                          '\n'
                                          '        return -self.phase_rad\n'
                                          '\n'
                                          '    @property\n'
                                          '    def rocker_pivot_x_ratio(self) -> float:\n'
                                          '        return self.ground_ratio * '
                                          'math.cos(self.ground_pivot_angle_rad)\n'
                                          '\n'
                                          '    @property\n'
                                          '    def rocker_pivot_y_ratio(self) -> float:\n'
                                          '        return self.ground_ratio * '
                                          'math.sin(self.ground_pivot_angle_rad)\n'
                                          '\n'
                                          '    def to_dict(self) -> dict[str, object]:\n'
                                          '        raw = asdict(self)\n'
                                          '        raw.update(\n'
                                          '            '
                                          'ground_pivot_angle_rad=self.ground_pivot_angle_rad,\n'
                                          '            '
                                          'rocker_pivot_x_ratio=self.rocker_pivot_x_ratio,\n'
                                          '            '
                                          'rocker_pivot_y_ratio=self.rocker_pivot_y_ratio,\n'
                                          '        )\n'
                                          '        return raw\n'
                                          '\n'
                                          '\n'
                                          '@dataclass(frozen=True, slots=True)\n'
                                          'class FourBarMotion:\n'
                                          '    """Vector basis functions and analytic derivatives '
                                          'over one sampled cycle."""\n'
                                          '\n'
                                          '    crank_xy: np.ndarray\n'
                                          '    crank_dxy_dtheta: np.ndarray\n'
                                          '    coupler_unit: np.ndarray\n'
                                          '    coupler_unit_derivative: np.ndarray\n'
                                          '    rocker_unit: np.ndarray\n'
                                          '    rocker_unit_derivative: np.ndarray\n'
                                          '    minimum_cross_product: float\n'
                                          '    outer_closure_margin: float\n'
                                          '    inner_closure_margin: float\n'
                                          '\n'
                                          '\n'
                                          '@dataclass(frozen=True, slots=True)\n'
                                          'class ProjectionRecovery:\n'
                                          '    """One physical representative of a projection fit '
                                          'in crank-radius units."""\n'
                                          '\n'
                                          '    axis_angle_canonical_rad: float\n'
                                          '    axis_angle_shared_crank_rad: float\n'
                                          '    output_along_ratio: float\n'
                                          '    output_normal_ratio: float\n'
                                          '    normalized_projection_scale: float\n'
                                          '\n'
                                          '    @property\n'
                                          '    def output_radius_ratio(self) -> float:\n'
                                          '        return math.hypot(self.output_along_ratio, '
                                          'self.output_normal_ratio)\n'
                                          '\n'
                                          '    def to_dict(self) -> dict[str, float]:\n'
                                          '        raw = asdict(self)\n'
                                          '        raw["output_radius_ratio"] = '
                                          'self.output_radius_ratio\n'
                                          '        return raw\n'
                                          '\n'
                                          '\n'
                                          '@dataclass(frozen=True, slots=True)\n'
                                          'class ProjectionFit:\n'
                                          '    output_type: OutputType\n'
                                          '    coefficients: tuple[float, ...]\n'
                                          '    position_rms: float\n'
                                          '    derivative_rms: float | None\n'
                                          '    maximum_absolute_position_error: float\n'
                                          '    objective_rms: float\n'
                                          '    recovery: ProjectionRecovery | None\n'
                                          '\n'
                                          '    def to_dict(self) -> dict[str, object]:\n'
                                          '        raw = asdict(self)\n'
                                          '        if self.recovery is not None:\n'
                                          '            raw["recovery"] = self.recovery.to_dict()\n'
                                          '        return raw\n'
                                          '\n'
                                          '\n'
                                          '@dataclass(frozen=True, slots=True)\n'
                                          'class ProjectionSearchResult:\n'
                                          '    geometry: NormalizedFourBarGeometry\n'
                                          '    fit: ProjectionFit\n'
                                          '    minimum_cross_product: float\n'
                                          '    outer_closure_margin: float\n'
                                          '    inner_closure_margin: float\n'
                                          '    optimizer_success: bool\n'
                                          '    optimizer_message: str\n'
                                          '    function_evaluations: int\n'
                                          '\n'
                                          '    def to_dict(self) -> dict[str, object]:\n'
                                          '        return {\n'
                                          '            "geometry": self.geometry.to_dict(),\n'
                                          '            "fit": self.fit.to_dict(),\n'
                                          '            "minimum_cross_product": '
                                          'self.minimum_cross_product,\n'
                                          '            "outer_closure_margin": '
                                          'self.outer_closure_margin,\n'
                                          '            "inner_closure_margin": '
                                          'self.inner_closure_margin,\n'
                                          '            "optimizer_success": '
                                          'self.optimizer_success,\n'
                                          '            "optimizer_message": '
                                          'self.optimizer_message,\n'
                                          '            "function_evaluations": '
                                          'self.function_evaluations,\n'
                                          '        }\n'
                                          '\n'
                                          '\n'
                                          'def evaluate_four_bar(\n'
                                          '    theta_rad: np.ndarray | tuple[float, ...],\n'
                                          '    geometry: NormalizedFourBarGeometry,\n'
                                          '    *,\n'
                                          '    singularity_tolerance: float = 1.0e-10,\n'
                                          ') -> FourBarMotion:\n'
                                          '    """Evaluate one complete-rotation four-bar with '
                                          'crank radius normalized to 1."""\n'
                                          '\n'
                                          '    theta = np.asarray(theta_rad, dtype=float)\n'
                                          '    if theta.ndim != 1 or theta.size < 4 or not '
                                          'np.all(np.isfinite(theta)):\n'
                                          '        raise ValueError("theta_rad must be a '
                                          'one-dimensional finite sample array.")\n'
                                          '    if not math.isfinite(singularity_tolerance) or '
                                          'singularity_tolerance <= 0.0:\n'
                                          '        raise ValueError("singularity_tolerance must be '
                                          'finite and positive.")\n'
                                          '\n'
                                          '    g = geometry.ground_ratio\n'
                                          '    c = geometry.coupler_ratio\n'
                                          '    r = geometry.rocker_ratio\n'
                                          '    scale = max(1.0, g, c, r)\n'
                                          '    tolerance = singularity_tolerance * scale\n'
                                          '\n'
                                          '    minimum_center_distance = abs(g - 1.0)\n'
                                          '    maximum_center_distance = g + 1.0\n'
                                          '    outer_margin = c + r - maximum_center_distance\n'
                                          '    inner_margin = minimum_center_distance - abs(c - '
                                          'r)\n'
                                          '    if minimum_center_distance <= tolerance:\n'
                                          '        raise ValueError("Four-bar circle centers '
                                          'coincide or nearly coincide during the cycle.")\n'
                                          '    if outer_margin <= tolerance:\n'
                                          '        raise ValueError("Four-bar cannot complete a '
                                          'crank revolution: outer closure limit.")\n'
                                          '    if inner_margin <= tolerance:\n'
                                          '        raise ValueError("Four-bar cannot complete a '
                                          'crank revolution: inner closure limit.")\n'
                                          '\n'
                                          '    crank_angle = theta + geometry.phase_rad\n'
                                          '    crank = np.column_stack((np.cos(crank_angle), '
                                          'np.sin(crank_angle)))\n'
                                          '    crank_derivative = '
                                          'np.column_stack((-np.sin(crank_angle), '
                                          'np.cos(crank_angle)))\n'
                                          '    pivot = np.array((g, 0.0), dtype=float)\n'
                                          '\n'
                                          '    delta = pivot - crank\n'
                                          '    distance = np.linalg.norm(delta, axis=1)\n'
                                          '    direction = delta / distance[:, None]\n'
                                          '    along = (c * c - r * r + distance * distance) / '
                                          '(2.0 * distance)\n'
                                          '    height_squared = c * c - along * along\n'
                                          '    if np.any(height_squared <= tolerance * '
                                          'tolerance):\n'
                                          '        raise ValueError("Four-bar reaches a toggle '
                                          'singularity.")\n'
                                          '    height = np.sqrt(height_squared)\n'
                                          '    left_normal = np.column_stack((-direction[:, 1], '
                                          'direction[:, 0]))\n'
                                          '    joint = (\n'
                                          '        crank\n'
                                          '        + along[:, None] * direction\n'
                                          '        + geometry.assembly_branch * height[:, None] * '
                                          'left_normal\n'
                                          '    )\n'
                                          '\n'
                                          '    coupler_vector = joint - crank\n'
                                          '    rocker_vector = joint - pivot\n'
                                          '    determinant = (\n'
                                          '        coupler_vector[:, 0] * rocker_vector[:, 1]\n'
                                          '        - coupler_vector[:, 1] * rocker_vector[:, 0]\n'
                                          '    )\n'
                                          '    if np.any(np.abs(determinant) <= '
                                          'singularity_tolerance * scale * scale):\n'
                                          '        raise ValueError("Four-bar velocity closure is '
                                          'singular.")\n'
                                          '\n'
                                          '    velocity_rhs = np.sum(coupler_vector * '
                                          'crank_derivative, axis=1)\n'
                                          '    joint_derivative = np.column_stack(\n'
                                          '        (\n'
                                          '            velocity_rhs * rocker_vector[:, 1] / '
                                          'determinant,\n'
                                          '            -velocity_rhs * rocker_vector[:, 0] / '
                                          'determinant,\n'
                                          '        )\n'
                                          '    )\n'
                                          '\n'
                                          '    coupler_unit = coupler_vector / c\n'
                                          '    rocker_unit = rocker_vector / r\n'
                                          '    coupler_unit_derivative = (joint_derivative - '
                                          'crank_derivative) / c\n'
                                          '    rocker_unit_derivative = joint_derivative / r\n'
                                          '    minimum_cross = float(np.min(np.abs(determinant) / '
                                          '(c * r)))\n'
                                          '\n'
                                          '    return FourBarMotion(\n'
                                          '        crank_xy=crank,\n'
                                          '        crank_dxy_dtheta=crank_derivative,\n'
                                          '        coupler_unit=coupler_unit,\n'
                                          '        '
                                          'coupler_unit_derivative=coupler_unit_derivative,\n'
                                          '        rocker_unit=rocker_unit,\n'
                                          '        rocker_unit_derivative=rocker_unit_derivative,\n'
                                          '        minimum_cross_product=minimum_cross,\n'
                                          '        outer_closure_margin=outer_margin,\n'
                                          '        inner_closure_margin=inner_margin,\n'
                                          '    )\n'
                                          '\n'
                                          '\n'
                                          'def projection_basis(\n'
                                          '    motion: FourBarMotion,\n'
                                          '    output_type: OutputType,\n'
                                          ') -> tuple[np.ndarray, np.ndarray]:\n'
                                          '    """Return the linear position basis and its '
                                          'analytic angular derivative."""\n'
                                          '\n'
                                          '    count = motion.crank_xy.shape[0]\n'
                                          '    ones = np.ones(count)\n'
                                          '    zeros = np.zeros(count)\n'
                                          '    if output_type == "rocker":\n'
                                          '        position = np.column_stack(\n'
                                          '            (ones, motion.rocker_unit[:, 0], '
                                          'motion.rocker_unit[:, 1])\n'
                                          '        )\n'
                                          '        derivative = np.column_stack(\n'
                                          '            (\n'
                                          '                zeros,\n'
                                          '                motion.rocker_unit_derivative[:, 0],\n'
                                          '                motion.rocker_unit_derivative[:, 1],\n'
                                          '            )\n'
                                          '        )\n'
                                          '    elif output_type == "coupler":\n'
                                          '        position = np.column_stack(\n'
                                          '            (\n'
                                          '                ones,\n'
                                          '                motion.crank_xy[:, 0],\n'
                                          '                motion.crank_xy[:, 1],\n'
                                          '                motion.coupler_unit[:, 0],\n'
                                          '                motion.coupler_unit[:, 1],\n'
                                          '            )\n'
                                          '        )\n'
                                          '        derivative = np.column_stack(\n'
                                          '            (\n'
                                          '                zeros,\n'
                                          '                motion.crank_dxy_dtheta[:, 0],\n'
                                          '                motion.crank_dxy_dtheta[:, 1],\n'
                                          '                motion.coupler_unit_derivative[:, 0],\n'
                                          '                motion.coupler_unit_derivative[:, 1],\n'
                                          '            )\n'
                                          '        )\n'
                                          '    else:\n'
                                          '        raise ValueError("output_type must be '
                                          '\'rocker\' or \'coupler\'.")\n'
                                          '    return position, derivative\n'
                                          '\n'
                                          '\n'
                                          'def _recover_projection(\n'
                                          '    coefficients: np.ndarray,\n'
                                          '    output_type: OutputType,\n'
                                          '    phase_rad: float,\n'
                                          ') -> ProjectionRecovery | None:\n'
                                          '    if output_type == "rocker":\n'
                                          '        x, y = float(coefficients[1]), '
                                          'float(coefficients[2])\n'
                                          '        scale = math.hypot(x, y)\n'
                                          '        if scale <= 64.0 * np.finfo(float).eps:\n'
                                          '            return None\n'
                                          '        axis = math.atan2(y, x)\n'
                                          '        # Gauge choice: place E one crank radius along '
                                          'the rocker. Any radial\n'
                                          '        # scaling is equivalent in projection-only '
                                          'synthesis and is absorbed by\n'
                                          '        # normalized_projection_scale.\n'
                                          '        return ProjectionRecovery(\n'
                                          '            axis_angle_canonical_rad=axis,\n'
                                          '            axis_angle_shared_crank_rad=axis - '
                                          'phase_rad,\n'
                                          '            output_along_ratio=1.0,\n'
                                          '            output_normal_ratio=0.0,\n'
                                          '            normalized_projection_scale=scale,\n'
                                          '        )\n'
                                          '\n'
                                          '    crank_x, crank_y = float(coefficients[1]), '
                                          'float(coefficients[2])\n'
                                          '    scale = math.hypot(crank_x, crank_y)\n'
                                          '    if scale <= 64.0 * np.finfo(float).eps:\n'
                                          '        return None\n'
                                          '    axis = math.atan2(crank_y, crank_x)\n'
                                          '    coupler_x, coupler_y = float(coefficients[3]), '
                                          'float(coefficients[4])\n'
                                          '    along = (coupler_x * math.cos(axis) + coupler_y * '
                                          'math.sin(axis)) / scale\n'
                                          '    normal = (coupler_x * math.sin(axis) - coupler_y * '
                                          'math.cos(axis)) / scale\n'
                                          '    return ProjectionRecovery(\n'
                                          '        axis_angle_canonical_rad=axis,\n'
                                          '        axis_angle_shared_crank_rad=axis - phase_rad,\n'
                                          '        output_along_ratio=along,\n'
                                          '        output_normal_ratio=normal,\n'
                                          '        normalized_projection_scale=scale,\n'
                                          '    )\n'
                                          '\n'
                                          '\n'
                                          'def fit_projection(\n'
                                          '    motion: FourBarMotion,\n'
                                          '    target_q: np.ndarray | tuple[float, ...],\n'
                                          '    *,\n'
                                          '    output_type: OutputType,\n'
                                          '    target_dq_dtheta: np.ndarray | tuple[float, ...] | '
                                          'None = None,\n'
                                          '    derivative_weight: float = 0.0,\n'
                                          '    phase_rad: float = 0.0,\n'
                                          ') -> ProjectionFit:\n'
                                          '    """Solve analytically for the best output '
                                          'point/projection coefficients."""\n'
                                          '\n'
                                          '    q = np.asarray(target_q, dtype=float)\n'
                                          '    if q.ndim != 1 or not np.all(np.isfinite(q)):\n'
                                          '        raise ValueError("target_q must be a '
                                          'one-dimensional finite array.")\n'
                                          '    position_basis, derivative_basis = '
                                          'projection_basis(motion, output_type)\n'
                                          '    if len(q) != position_basis.shape[0]:\n'
                                          '        raise ValueError("target_q sample count does '
                                          'not match the four-bar motion.")\n'
                                          '    if not math.isfinite(derivative_weight) or '
                                          'derivative_weight < 0.0:\n'
                                          '        raise ValueError("derivative_weight must be '
                                          'finite and non-negative.")\n'
                                          '\n'
                                          '    dq = None\n'
                                          '    if target_dq_dtheta is not None:\n'
                                          '        dq = np.asarray(target_dq_dtheta, dtype=float)\n'
                                          '        if dq.shape != q.shape or not '
                                          'np.all(np.isfinite(dq)):\n'
                                          '            raise ValueError("target_dq_dtheta must '
                                          'match target_q with finite values.")\n'
                                          '    if derivative_weight > 0.0 and dq is None:\n'
                                          '        raise ValueError("A derivative target is '
                                          'required when derivative_weight is positive.")\n'
                                          '\n'
                                          '    if derivative_weight > 0.0:\n'
                                          '        root_weight = math.sqrt(derivative_weight)\n'
                                          '        matrix = np.vstack((position_basis, root_weight '
                                          '* derivative_basis))\n'
                                          '        rhs = np.concatenate((q, root_weight * dq))\n'
                                          '    else:\n'
                                          '        matrix = position_basis\n'
                                          '        rhs = q\n'
                                          '\n'
                                          '    coefficients, *_ = np.linalg.lstsq(matrix, rhs, '
                                          'rcond=None)\n'
                                          '    predicted = position_basis @ coefficients\n'
                                          '    position_error = predicted - q\n'
                                          '    position_rms = float(np.sqrt(np.mean(position_error '
                                          '* position_error)))\n'
                                          '    maximum_error = '
                                          'float(np.max(np.abs(position_error)))\n'
                                          '\n'
                                          '    derivative_rms = None\n'
                                          '    derivative_term = 0.0\n'
                                          '    if dq is not None:\n'
                                          '        derivative_error = derivative_basis @ '
                                          'coefficients - dq\n'
                                          '        derivative_rms = '
                                          'float(np.sqrt(np.mean(derivative_error * '
                                          'derivative_error)))\n'
                                          '        derivative_term = derivative_weight * '
                                          'derivative_rms * derivative_rms\n'
                                          '    objective_rms = math.sqrt(position_rms * '
                                          'position_rms + derivative_term)\n'
                                          '\n'
                                          '    return ProjectionFit(\n'
                                          '        output_type=output_type,\n'
                                          '        coefficients=tuple(float(value) for value in '
                                          'coefficients),\n'
                                          '        position_rms=position_rms,\n'
                                          '        derivative_rms=derivative_rms,\n'
                                          '        maximum_absolute_position_error=maximum_error,\n'
                                          '        objective_rms=objective_rms,\n'
                                          '        recovery=_recover_projection(coefficients, '
                                          'output_type, phase_rad),\n'
                                          '    )\n'
                                          '\n'
                                          '\n'
                                          'def search_projection(\n'
                                          '    theta_rad: np.ndarray | tuple[float, ...],\n'
                                          '    target_q: np.ndarray | tuple[float, ...],\n'
                                          '    *,\n'
                                          '    output_type: OutputType,\n'
                                          '    assembly_branch: int,\n'
                                          '    target_dq_dtheta: np.ndarray | tuple[float, ...] | '
                                          'None = None,\n'
                                          '    derivative_weight: float = 0.0,\n'
                                          '    ratio_minimum: float = 0.2,\n'
                                          '    ratio_maximum: float = 6.0,\n'
                                          '    maximum_iterations: int = 80,\n'
                                          '    population_size: int = 10,\n'
                                          '    seed: int = 27,\n'
                                          ') -> ProjectionSearchResult:\n'
                                          '    """Search three link ratios and phase; solve output '
                                          'coordinates analytically."""\n'
                                          '\n'
                                          '    if assembly_branch not in (-1, 1):\n'
                                          '        raise ValueError("assembly_branch must be -1 or '
                                          '1.")\n'
                                          '    for name, value in (("ratio_minimum", '
                                          'ratio_minimum), ("ratio_maximum", ratio_maximum)):\n'
                                          '        if not math.isfinite(value) or value <= 0.0:\n'
                                          '            raise ValueError(f"{name} must be finite '
                                          'and positive.")\n'
                                          '    if ratio_maximum <= ratio_minimum:\n'
                                          '        raise ValueError("ratio_maximum must exceed '
                                          'ratio_minimum.")\n'
                                          '    if maximum_iterations <= 0 or population_size < 4:\n'
                                          '        raise ValueError("Search iteration and '
                                          'population limits are too small.")\n'
                                          '\n'
                                          '    theta = np.asarray(theta_rad, dtype=float)\n'
                                          '    q = np.asarray(target_q, dtype=float)\n'
                                          '    dq = None if target_dq_dtheta is None else '
                                          'np.asarray(target_dq_dtheta, dtype=float)\n'
                                          '    invalid_penalty = 1.0e6\n'
                                          '\n'
                                          '    def objective(vector: np.ndarray) -> float:\n'
                                          '        geometry = NormalizedFourBarGeometry(\n'
                                          '            ground_ratio=math.exp(float(vector[0])),\n'
                                          '            coupler_ratio=math.exp(float(vector[1])),\n'
                                          '            rocker_ratio=math.exp(float(vector[2])),\n'
                                          '            phase_rad=float(vector[3]),\n'
                                          '            assembly_branch=assembly_branch,\n'
                                          '        )\n'
                                          '        try:\n'
                                          '            motion = evaluate_four_bar(theta, '
                                          'geometry)\n'
                                          '            fit = fit_projection(\n'
                                          '                motion,\n'
                                          '                q,\n'
                                          '                output_type=output_type,\n'
                                          '                target_dq_dtheta=dq,\n'
                                          '                derivative_weight=derivative_weight,\n'
                                          '                phase_rad=geometry.phase_rad,\n'
                                          '            )\n'
                                          '        except (ValueError, FloatingPointError, '
                                          'np.linalg.LinAlgError):\n'
                                          '            return invalid_penalty\n'
                                          '        return fit.objective_rms\n'
                                          '\n'
                                          '    logarithmic_bounds = (math.log(ratio_minimum), '
                                          'math.log(ratio_maximum))\n'
                                          '    result = differential_evolution(\n'
                                          '        objective,\n'
                                          '        bounds=(\n'
                                          '            logarithmic_bounds,\n'
                                          '            logarithmic_bounds,\n'
                                          '            logarithmic_bounds,\n'
                                          '            (-math.pi, math.pi),\n'
                                          '        ),\n'
                                          '        maxiter=maximum_iterations,\n'
                                          '        popsize=population_size,\n'
                                          '        seed=seed,\n'
                                          '        polish=True,\n'
                                          '        tol=1.0e-7,\n'
                                          '        updating="immediate",\n'
                                          '        workers=1,\n'
                                          '    )\n'
                                          '    if not math.isfinite(float(result.fun)) or '
                                          'float(result.fun) >= invalid_penalty:\n'
                                          '        raise ValueError("Search did not find a '
                                          'complete-rotation four-bar geometry.")\n'
                                          '\n'
                                          '    geometry = NormalizedFourBarGeometry(\n'
                                          '        ground_ratio=math.exp(float(result.x[0])),\n'
                                          '        coupler_ratio=math.exp(float(result.x[1])),\n'
                                          '        rocker_ratio=math.exp(float(result.x[2])),\n'
                                          '        phase_rad=float(result.x[3]),\n'
                                          '        assembly_branch=assembly_branch,\n'
                                          '    )\n'
                                          '    motion = evaluate_four_bar(theta, geometry)\n'
                                          '    fit = fit_projection(\n'
                                          '        motion,\n'
                                          '        q,\n'
                                          '        output_type=output_type,\n'
                                          '        target_dq_dtheta=dq,\n'
                                          '        derivative_weight=derivative_weight,\n'
                                          '        phase_rad=geometry.phase_rad,\n'
                                          '    )\n'
                                          '    return ProjectionSearchResult(\n'
                                          '        geometry=geometry,\n'
                                          '        fit=fit,\n'
                                          '        '
                                          'minimum_cross_product=motion.minimum_cross_product,\n'
                                          '        '
                                          'outer_closure_margin=motion.outer_closure_margin,\n'
                                          '        '
                                          'inner_closure_margin=motion.inner_closure_margin,\n'
                                          '        optimizer_success=bool(result.success),\n'
                                          '        optimizer_message=str(result.message),\n'
                                          '        function_evaluations=int(result.nfev),\n'
                                          '    )\n',
 'src/dada_4bar_synthesis/cli.py': '"""Command-line entry point for projection-only four-bar '
                                   'synthesis."""\n'
                                   '\n'
                                   'from __future__ import annotations\n'
                                   '\n'
                                   'import argparse\n'
                                   'import json\n'
                                   'import math\n'
                                   'from pathlib import Path\n'
                                   '\n'
                                   'from .io import load_solver_motion_target\n'
                                   'from .projection import search_projection\n'
                                   '\n'
                                   '\n'
                                   'def _parser() -> argparse.ArgumentParser:\n'
                                   '    parser = argparse.ArgumentParser(\n'
                                   '        description=(\n'
                                   '            "Fit normalized DADA motion targets with a '
                                   'four-bar output in pure projection."\n'
                                   '        )\n'
                                   '    )\n'
                                   '    parser.add_argument("target_csv", type=Path)\n'
                                   '    parser.add_argument("--target-json", type=Path, '
                                   'default=None)\n'
                                   '    parser.add_argument("--side", choices=("small", "large", '
                                   '"both"), default="both")\n'
                                   '    parser.add_argument(\n'
                                   '        "--output-type", choices=("rocker", "coupler", '
                                   '"both"), default="both"\n'
                                   '    )\n'
                                   '    parser.add_argument("--branch", choices=("-1", "1", '
                                   '"both"), default="both")\n'
                                   '    parser.add_argument("--derivative-weight", type=float, '
                                   'default=0.0)\n'
                                   '    parser.add_argument("--ratio-minimum", type=float, '
                                   'default=0.2)\n'
                                   '    parser.add_argument("--ratio-maximum", type=float, '
                                   'default=6.0)\n'
                                   '    parser.add_argument("--maximum-iterations", type=int, '
                                   'default=80)\n'
                                   '    parser.add_argument("--population-size", type=int, '
                                   'default=10)\n'
                                   '    parser.add_argument("--seed", type=int, default=27)\n'
                                   '    parser.add_argument("--result-json", type=Path, '
                                   'default=None)\n'
                                   '    return parser\n'
                                   '\n'
                                   '\n'
                                   'def main(argv: list[str] | None = None) -> int:\n'
                                   '    args = _parser().parse_args(argv)\n'
                                   '    target = load_solver_motion_target(args.target_csv, '
                                   'args.target_json)\n'
                                   '\n'
                                   '    sides = ("small", "large") if args.side == "both" else '
                                   '(args.side,)\n'
                                   '    output_types = (\n'
                                   '        ("rocker", "coupler") if args.output_type == "both" '
                                   'else (args.output_type,)\n'
                                   '    )\n'
                                   '    branches = (-1, 1) if args.branch == "both" else '
                                   '(int(args.branch),)\n'
                                   '\n'
                                   '    records: list[dict[str, object]] = []\n'
                                   '    search_index = 0\n'
                                   '    for side in sides:\n'
                                   '        q = target.small_q if side == "small" else '
                                   'target.large_q\n'
                                   '        dq = target.small_dq_dtheta if side == "small" else '
                                   'target.large_dq_dtheta\n'
                                   '        for output_type in output_types:\n'
                                   '            for branch in branches:\n'
                                   '                result = search_projection(\n'
                                   '                    target.theta_rad,\n'
                                   '                    q,\n'
                                   '                    output_type=output_type,\n'
                                   '                    assembly_branch=branch,\n'
                                   '                    target_dq_dtheta=dq,\n'
                                   '                    derivative_weight=args.derivative_weight,\n'
                                   '                    ratio_minimum=args.ratio_minimum,\n'
                                   '                    ratio_maximum=args.ratio_maximum,\n'
                                   '                    '
                                   'maximum_iterations=args.maximum_iterations,\n'
                                   '                    population_size=args.population_size,\n'
                                   '                    seed=args.seed + search_index,\n'
                                   '                )\n'
                                   '                search_index += 1\n'
                                   '                record = {\n'
                                   '                    "side": side,\n'
                                   '                    "output_type": output_type,\n'
                                   '                    "assembly_branch": branch,\n'
                                   '                    **result.to_dict(),\n'
                                   '                }\n'
                                   '                records.append(record)\n'
                                   '\n'
                                   '    records.sort(key=lambda item: '
                                   'float(item["fit"]["objective_rms"]))\n'
                                   '\n'
                                   '    for rank, record in enumerate(records, start=1):\n'
                                   '        fit = record["fit"]\n'
                                   '        geometry = record["geometry"]\n'
                                   '        recovery = fit.get("recovery")\n'
                                   '        derivative = fit["derivative_rms"]\n'
                                   '        print(\n'
                                   '            f"{rank:2d} {record[\'side\']:5s} '
                                   '{record[\'output_type\']:7s} "\n'
                                   '            f"branch={record[\'assembly_branch\']:+d} "\n'
                                   '            f"RMS={fit[\'position_rms\']:.8g} "\n'
                                   '            f"dRMS={\'-\' if derivative is None else '
                                   'f\'{derivative:.8g}\'}"\n'
                                   '        )\n'
                                   '        print(\n'
                                   '            "   "\n'
                                   '            f"ground/crank={geometry[\'ground_ratio\']:.8g} "\n'
                                   '            f"coupler/crank={geometry[\'coupler_ratio\']:.8g} '
                                   '"\n'
                                   '            f"rocker/crank={geometry[\'rocker_ratio\']:.8g} "\n'
                                   '            '
                                   'f"pivot_angle={math.degrees(geometry[\'ground_pivot_angle_rad\']):.4f} '
                                   'deg "\n'
                                   '            '
                                   'f"min_cross={record[\'minimum_cross_product\']:.6g}"\n'
                                   '        )\n'
                                   '        if recovery is not None:\n'
                                   '            print(\n'
                                   '                "   "\n'
                                   '                '
                                   'f"axis={math.degrees(recovery[\'axis_angle_shared_crank_rad\']):.4f} '
                                   'deg "\n'
                                   '                '
                                   'f"output_along/crank={recovery[\'output_along_ratio\']:.8g} "\n'
                                   '                '
                                   'f"output_normal/crank={recovery[\'output_normal_ratio\']:.8g} '
                                   '"\n'
                                   '                '
                                   'f"output_radius/crank={recovery[\'output_radius_ratio\']:.8g}"\n'
                                   '            )\n'
                                   '\n'
                                   '    if args.result_json is not None:\n'
                                   '        payload = {\n'
                                   '            "schema_version": 1,\n'
                                   '            "method": "projection_only_linear_output_fit",\n'
                                   '            "target_csv": str(args.target_csv),\n'
                                   '            "target_json": None if args.target_json is None '
                                   'else str(args.target_json),\n'
                                   '            "settings": {\n'
                                   '                "side": args.side,\n'
                                   '                "output_type": args.output_type,\n'
                                   '                "branch": args.branch,\n'
                                   '                "derivative_weight": args.derivative_weight,\n'
                                   '                "ratio_minimum": args.ratio_minimum,\n'
                                   '                "ratio_maximum": args.ratio_maximum,\n'
                                   '                "maximum_iterations": '
                                   'args.maximum_iterations,\n'
                                   '                "population_size": args.population_size,\n'
                                   '                "seed": args.seed,\n'
                                   '            },\n'
                                   '            "results": records,\n'
                                   '        }\n'
                                   '        args.result_json.parent.mkdir(parents=True, '
                                   'exist_ok=True)\n'
                                   '        args.result_json.write_text(json.dumps(payload, '
                                   'indent=2) + "\\n", encoding="utf-8")\n'
                                   '\n'
                                   '    return 0\n'
                                   '\n'
                                   '\n'
                                   'if __name__ == "__main__":\n'
                                   '    raise SystemExit(main())\n',
 'src/dada_4bar_synthesis/__main__.py': 'from .cli import main\n\nraise SystemExit(main())\n',
 'src/dada_4bar_synthesis/__init__.py': '"""Inverse four-bar synthesis for DADA engine '
                                        'kinematics."""\n'
                                        '\n'
                                        'from .contracts import (\n'
                                        '    AssemblyContract,\n'
                                        '    CylinderTargetLimits,\n'
                                        '    FourBarLoopContract,\n'
                                        '    FreeKinematicsTarget,\n'
                                        '    FreeMotionTarget,\n'
                                        '    OutputPointContract,\n'
                                        '    SampledMotionTarget,\n'
                                        '    SharedCrankFourBarContract,\n'
                                        '    SliderConstraintContract,\n'
                                        ')\n'
                                        'from .io import load_solver_free_kinematics_target, '
                                        'load_solver_motion_target\n'
                                        'from .projection import (\n'
                                        '    FourBarMotion,\n'
                                        '    NormalizedFourBarGeometry,\n'
                                        '    ProjectionFit,\n'
                                        '    ProjectionRecovery,\n'
                                        '    ProjectionSearchResult,\n'
                                        '    evaluate_four_bar,\n'
                                        '    fit_projection,\n'
                                        '    projection_basis,\n'
                                        '    search_projection,\n'
                                        ')\n'
                                        '\n'
                                        '__all__ = [\n'
                                        '    "AssemblyContract",\n'
                                        '    "CylinderTargetLimits",\n'
                                        '    "FourBarLoopContract",\n'
                                        '    "FreeKinematicsTarget",\n'
                                        '    "FreeMotionTarget",\n'
                                        '    "OutputPointContract",\n'
                                        '    "SampledMotionTarget",\n'
                                        '    "SharedCrankFourBarContract",\n'
                                        '    "SliderConstraintContract",\n'
                                        '    "load_solver_free_kinematics_target",\n'
                                        '    "load_solver_motion_target",\n'
                                        '    "FourBarMotion",\n'
                                        '    "NormalizedFourBarGeometry",\n'
                                        '    "ProjectionFit",\n'
                                        '    "ProjectionRecovery",\n'
                                        '    "ProjectionSearchResult",\n'
                                        '    "evaluate_four_bar",\n'
                                        '    "fit_projection",\n'
                                        '    "projection_basis",\n'
                                        '    "search_projection",\n'
                                        ']\n',
 'tests/test_projection.py': 'import math\n'
                             '\n'
                             'import numpy as np\n'
                             'import pytest\n'
                             '\n'
                             'from dada_4bar_synthesis.projection import (\n'
                             '    NormalizedFourBarGeometry,\n'
                             '    evaluate_four_bar,\n'
                             '    fit_projection,\n'
                             '    projection_basis,\n'
                             '    search_projection,\n'
                             ')\n'
                             '\n'
                             '\n'
                             'def angles(count=360):\n'
                             '    return np.linspace(0.0, 2.0 * math.pi, count, endpoint=False)\n'
                             '\n'
                             '\n'
                             'def geometry(branch=-1):\n'
                             '    return NormalizedFourBarGeometry(2.0, 1.7, 1.6, 0.4, branch)\n'
                             '\n'
                             '\n'
                             'def test_analytic_basis_derivatives_match_centered_difference():\n'
                             '    theta = angles(180)\n'
                             '    item = geometry()\n'
                             '    motion = evaluate_four_bar(theta, item)\n'
                             '    step = 1.0e-6\n'
                             '    before = evaluate_four_bar(theta - step, item)\n'
                             '    after = evaluate_four_bar(theta + step, item)\n'
                             '\n'
                             '    np.testing.assert_allclose(\n'
                             '        motion.rocker_unit_derivative,\n'
                             '        (after.rocker_unit - before.rocker_unit) / (2.0 * step),\n'
                             '        rtol=2e-8,\n'
                             '        atol=2e-9,\n'
                             '    )\n'
                             '    np.testing.assert_allclose(\n'
                             '        motion.coupler_unit_derivative,\n'
                             '        (after.coupler_unit - before.coupler_unit) / (2.0 * step),\n'
                             '        rtol=2e-8,\n'
                             '        atol=2e-9,\n'
                             '    )\n'
                             '\n'
                             '\n'
                             'def test_rejects_geometry_that_cannot_complete_a_revolution():\n'
                             '    with pytest.raises(ValueError, match="outer closure"):\n'
                             '        evaluate_four_bar(angles(), NormalizedFourBarGeometry(2.0, '
                             '1.0, 1.0))\n'
                             '\n'
                             '\n'
                             'def test_rocker_projection_is_recovered_exactly():\n'
                             '    motion = evaluate_four_bar(angles(), geometry())\n'
                             '    position, derivative = projection_basis(motion, "rocker")\n'
                             '    exact = np.array((0.13, 0.72, -0.31))\n'
                             '    q = position @ exact\n'
                             '    dq = derivative @ exact\n'
                             '\n'
                             '    fit = fit_projection(\n'
                             '        motion,\n'
                             '        q,\n'
                             '        output_type="rocker",\n'
                             '        target_dq_dtheta=dq,\n'
                             '        derivative_weight=0.3,\n'
                             '        phase_rad=geometry().phase_rad,\n'
                             '    )\n'
                             '\n'
                             '    assert fit.position_rms < 1e-12\n'
                             '    assert fit.derivative_rms is not None and fit.derivative_rms < '
                             '1e-12\n'
                             '    assert fit.coefficients == pytest.approx(exact, abs=1e-12)\n'
                             '    assert fit.recovery is not None\n'
                             '    assert fit.recovery.output_along_ratio == pytest.approx(1.0)\n'
                             '    assert fit.recovery.output_normal_ratio == pytest.approx(0.0)\n'
                             '\n'
                             '\n'
                             'def test_coupler_projection_recovers_physical_point():\n'
                             '    motion = evaluate_four_bar(angles(), geometry())\n'
                             '    axis = 0.7\n'
                             '    scale = 0.8\n'
                             '    along = 1.25\n'
                             '    normal = -0.45\n'
                             '    coefficients = np.array(\n'
                             '        (\n'
                             '            -0.11,\n'
                             '            scale * math.cos(axis),\n'
                             '            scale * math.sin(axis),\n'
                             '            scale * (along * math.cos(axis) + normal * '
                             'math.sin(axis)),\n'
                             '            scale * (along * math.sin(axis) - normal * '
                             'math.cos(axis)),\n'
                             '        )\n'
                             '    )\n'
                             '    position, derivative = projection_basis(motion, "coupler")\n'
                             '    q = position @ coefficients\n'
                             '    dq = derivative @ coefficients\n'
                             '\n'
                             '    fit = fit_projection(\n'
                             '        motion,\n'
                             '        q,\n'
                             '        output_type="coupler",\n'
                             '        target_dq_dtheta=dq,\n'
                             '        derivative_weight=0.2,\n'
                             '        phase_rad=geometry().phase_rad,\n'
                             '    )\n'
                             '\n'
                             '    assert fit.position_rms < 1e-12\n'
                             '    assert fit.recovery is not None\n'
                             '    assert fit.recovery.axis_angle_canonical_rad == '
                             'pytest.approx(axis)\n'
                             '    assert fit.recovery.axis_angle_shared_crank_rad == '
                             'pytest.approx(axis - 0.4)\n'
                             '    assert fit.recovery.output_along_ratio == pytest.approx(along)\n'
                             '    assert fit.recovery.output_normal_ratio == '
                             'pytest.approx(normal)\n'
                             '    assert fit.recovery.normalized_projection_scale == '
                             'pytest.approx(scale)\n'
                             '\n'
                             '\n'
                             'def test_search_recovers_a_synthetic_coupler_target():\n'
                             '    theta = angles(240)\n'
                             '    true_geometry = geometry()\n'
                             '    motion = evaluate_four_bar(theta, true_geometry)\n'
                             '    position, derivative = projection_basis(motion, "coupler")\n'
                             '    coefficients = np.array((-0.1, 0.4, 0.7, 1.2, -0.5))\n'
                             '    q = position @ coefficients\n'
                             '    dq = derivative @ coefficients\n'
                             '\n'
                             '    result = search_projection(\n'
                             '        theta,\n'
                             '        q,\n'
                             '        output_type="coupler",\n'
                             '        assembly_branch=-1,\n'
                             '        target_dq_dtheta=dq,\n'
                             '        ratio_minimum=1.0,\n'
                             '        ratio_maximum=2.6,\n'
                             '        maximum_iterations=35,\n'
                             '        population_size=8,\n'
                             '        seed=3,\n'
                             '    )\n'
                             '\n'
                             '    assert result.fit.position_rms < 2e-5\n'}

for name, content in FILES.items():
    path = Path(name)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
    print(f"wrote {path}")

pyproject = Path("pyproject.toml")
text = pyproject.read_text(encoding="utf-8")
if "[project.scripts]" not in text:
    marker = "[project.optional-dependencies]"
    if marker not in text:
        raise SystemExit("Could not find [project.optional-dependencies] in pyproject.toml")
    text = text.replace(
        marker,
        '[project.scripts]\ndada-4bar-synthesis = "dada_4bar_synthesis.cli:main"\n\n' + marker,
        1,
    )
    pyproject.write_text(text, encoding="utf-8")
    print("updated pyproject.toml")
else:
    print("pyproject.toml already has [project.scripts]; left unchanged")

print("\nNext:")
print("  python -m pip install -e '.[test]'")
print("  python -m pytest")
print("")
print("Then, for the current champion:")
print("  python -m dada_4bar_synthesis ../dada-engine-solver/outputs/motor_champion_motion_target.csv \\")
print("    --result-json outputs/champion_projection_search.json")
