#!/usr/bin/env python3
from pathlib import Path

FILES = {'pyproject.toml': '[build-system]\n'
                   'requires = ["setuptools>=66.1"]\n'
                   'build-backend = "setuptools.build_meta"\n'
                   '\n'
                   '[project]\n'
                   'name = "dada-4bar-synthesis"\n'
                   'version = "0.1.0"\n'
                   'description = "Inverse kinematic synthesis of four-bar mechanisms for the DADA '
                   'engine"\n'
                   'readme = "README.md"\n'
                   'license = { text = "GPL-3.0-or-later" }\n'
                   'requires-python = ">=3.11"\n'
                   'dependencies = [\n'
                   '    "numpy>=1.24",\n'
                   '    "scipy>=1.10",\n'
                   ']\n'
                   '\n'
                   '[project.optional-dependencies]\n'
                   'test = ["pytest>=7.2"]\n'
                   '\n'
                   '[tool.setuptools.packages.find]\n'
                   'where = ["src"]\n'
                   '\n'
                   '[tool.setuptools]\n'
                   'license-files = ["LICENSE"]\n'
                   '\n'
                   '[tool.pytest.ini_options]\n'
                   'addopts = "-ra"\n'
                   'testpaths = ["tests"]\n',
 'README.md': '# dada-4bar-synthesis\n'
              '\n'
              'Inverse kinematic synthesis of four-bar mechanisms for the DADA engine.\n'
              '\n'
              'This repository is deliberately separate from `dada-engine-solver`.\n'
              '\n'
              'Its role is:\n'
              '\n'
              '1. read a target kinematic law produced/used by `dada-engine-solver`;\n'
              '2. search for a realizable four-bar mechanism reproducing that law;\n'
              '3. export a mechanical definition directly mappable to the existing\n'
              '   `dada_solver.four_bar` classes.\n'
              '\n'
              'The thermodynamic solver remains authoritative for thermodynamics. This project\n'
              'does not duplicate its thermodynamic model.\n'
              '\n'
              '## I/O contract\n'
              '\n'
              '### Input\n'
              '\n'
              'The first supported input is a normal `dada-engine-solver` TOML configuration\n'
              'using `[kinematics] type = "free"` with `control_values` for the small and large\n'
              'cylinders. Cylinder volume limits are read from the existing `[geometry]`\n'
              'fields.\n'
              '\n'
              'Angles use the solver study-angle convention: radians internally, one cycle is\n'
              '`2*pi`.\n'
              '\n'
              '### Output\n'
              '\n'
              'The synthesis result mirrors the low-level types already present in\n'
              '`dada_solver.four_bar`:\n'
              '\n'
              '- `FourBarLoop`\n'
              '- `RockerOutputPoint` or `CouplerOutputPoint`\n'
              '- `SliderConstraint`\n'
              '- `SharedCrankFourBarVolumeKinematics`\n'
              '\n'
              'No alternative mechanical convention is introduced here.\n'
              '\n'
              'Version 0.1 intentionally contains only target-law I/O, result-contract\n'
              'dataclasses, validation, and tests. The mathematical synthesis is added on top\n'
              'of this contract.\n',
 'src/dada_4bar_synthesis/__init__.py': '"""Inverse four-bar synthesis for DADA engine '
                                        'kinematics."""\n'
                                        '\n'
                                        'from .contracts import (\n'
                                        '    AssemblyContract,\n'
                                        '    FourBarLoopContract,\n'
                                        '    FreeKinematicsTarget,\n'
                                        '    FreeMotionTarget,\n'
                                        '    OutputPointContract,\n'
                                        '    SharedCrankFourBarContract,\n'
                                        '    SliderConstraintContract,\n'
                                        ')\n'
                                        'from .io import load_solver_free_kinematics_target\n'
                                        '\n'
                                        '__all__ = [\n'
                                        '    "AssemblyContract",\n'
                                        '    "FourBarLoopContract",\n'
                                        '    "FreeKinematicsTarget",\n'
                                        '    "FreeMotionTarget",\n'
                                        '    "OutputPointContract",\n'
                                        '    "SharedCrankFourBarContract",\n'
                                        '    "SliderConstraintContract",\n'
                                        '    "load_solver_free_kinematics_target",\n'
                                        ']\n',
 'src/dada_4bar_synthesis/contracts.py': '"""Versioned I/O contracts aligned with '
                                         'dada-engine-solver conventions."""\n'
                                         '\n'
                                         'from __future__ import annotations\n'
                                         '\n'
                                         'from dataclasses import asdict, dataclass\n'
                                         'import math\n'
                                         'from typing import Literal\n'
                                         '\n'
                                         '\n'
                                         'def _finite(name: str, value: float) -> None:\n'
                                         '    if not math.isfinite(value):\n'
                                         '        raise ValueError(f"{name} must be finite.")\n'
                                         '\n'
                                         '\n'
                                         'def _positive(name: str, value: float) -> None:\n'
                                         '    _finite(name, value)\n'
                                         '    if value <= 0.0:\n'
                                         '        raise ValueError(f"{name} must be positive.")\n'
                                         '\n'
                                         '\n'
                                         '@dataclass(frozen=True, slots=True)\n'
                                         'class FreeMotionTarget:\n'
                                         '    """One free volume law as represented by '
                                         'dada-engine-solver."""\n'
                                         '\n'
                                         '    control_values: tuple[float, ...]\n'
                                         '    minimum_volume: float\n'
                                         '    maximum_volume: float\n'
                                         '    maximum_absolute_first_derivative: float | None = '
                                         'None\n'
                                         '    maximum_absolute_second_derivative: float | None = '
                                         'None\n'
                                         '\n'
                                         '    def __post_init__(self) -> None:\n'
                                         '        if len(self.control_values) < 4:\n'
                                         '            raise ValueError("At least four control '
                                         'values are required.")\n'
                                         '        if not all(math.isfinite(v) for v in '
                                         'self.control_values):\n'
                                         '            raise ValueError("Control values must be '
                                         'finite.")\n'
                                         '        _positive("minimum volume", '
                                         'self.minimum_volume)\n'
                                         '        _positive("maximum volume", '
                                         'self.maximum_volume)\n'
                                         '        if self.maximum_volume <= self.minimum_volume:\n'
                                         '            raise ValueError("Maximum volume must exceed '
                                         'minimum volume.")\n'
                                         '        for name, value in (\n'
                                         '            ("maximum absolute first derivative",\n'
                                         '             self.maximum_absolute_first_derivative),\n'
                                         '            ("maximum absolute second derivative",\n'
                                         '             self.maximum_absolute_second_derivative),\n'
                                         '        ):\n'
                                         '            if value is not None:\n'
                                         '                _finite(name, value)\n'
                                         '                if value < 0.0:\n'
                                         '                    raise ValueError(f"{name} must be '
                                         'non-negative.")\n'
                                         '\n'
                                         '\n'
                                         '@dataclass(frozen=True, slots=True)\n'
                                         'class FreeKinematicsTarget:\n'
                                         '    """Two-cylinder target law in the solver study-angle '
                                         'convention."""\n'
                                         '\n'
                                         '    small: FreeMotionTarget\n'
                                         '    large: FreeMotionTarget\n'
                                         '    angle_convention: str = "study_angle_radians"\n'
                                         '    cycle_angle: float = 2.0 * math.pi\n'
                                         '    source_kinematics_type: str = "free"\n'
                                         '\n'
                                         '    def __post_init__(self) -> None:\n'
                                         '        if self.angle_convention != '
                                         '"study_angle_radians":\n'
                                         '            raise ValueError("Unsupported angle '
                                         'convention.")\n'
                                         '        if not math.isclose(self.cycle_angle, 2.0 * '
                                         'math.pi):\n'
                                         '            raise ValueError("A DADA kinematic cycle '
                                         'must be 2*pi radians.")\n'
                                         '        if self.source_kinematics_type != "free":\n'
                                         '            raise ValueError("Initial synthesis contract '
                                         'accepts free kinematics only.")\n'
                                         '\n'
                                         '\n'
                                         '@dataclass(frozen=True, slots=True)\n'
                                         'class FourBarLoopContract:\n'
                                         '    """Direct counterpart of '
                                         'dada_solver.four_bar.FourBarLoop."""\n'
                                         '\n'
                                         '    coupler_length: float\n'
                                         '    rocker_length: float\n'
                                         '    rocker_pivot_x: float\n'
                                         '    rocker_pivot_y: float\n'
                                         '    assembly_branch: int = 1\n'
                                         '\n'
                                         '    def __post_init__(self) -> None:\n'
                                         '        _positive("coupler length", '
                                         'self.coupler_length)\n'
                                         '        _positive("rocker length", self.rocker_length)\n'
                                         '        _finite("rocker pivot x", self.rocker_pivot_x)\n'
                                         '        _finite("rocker pivot y", self.rocker_pivot_y)\n'
                                         '        if self.assembly_branch not in (-1, 1):\n'
                                         '            raise ValueError("assembly_branch must be -1 '
                                         'or 1.")\n'
                                         '\n'
                                         '\n'
                                         '@dataclass(frozen=True, slots=True)\n'
                                         'class OutputPointContract:\n'
                                         '    """Counterpart of RockerOutputPoint or '
                                         'CouplerOutputPoint."""\n'
                                         '\n'
                                         '    type: Literal["rocker", "coupler"]\n'
                                         '    along: float\n'
                                         '    normal: float = 0.0\n'
                                         '\n'
                                         '    def __post_init__(self) -> None:\n'
                                         '        if self.type not in ("rocker", "coupler"):\n'
                                         '            raise ValueError("Output type must be '
                                         '\'rocker\' or \'coupler\'.")\n'
                                         '        _finite("output along coordinate", self.along)\n'
                                         '        _finite("output normal coordinate", '
                                         'self.normal)\n'
                                         '\n'
                                         '\n'
                                         '@dataclass(frozen=True, slots=True)\n'
                                         'class SliderConstraintContract:\n'
                                         '    """Direct counterpart of '
                                         'dada_solver.four_bar.SliderConstraint."""\n'
                                         '\n'
                                         '    axis_origin_x: float\n'
                                         '    axis_origin_y: float\n'
                                         '    axis_angle: float\n'
                                         '    connecting_rod_length: float\n'
                                         '    assembly_branch: int = 1\n'
                                         '\n'
                                         '    def __post_init__(self) -> None:\n'
                                         '        _finite("slider axis origin x", '
                                         'self.axis_origin_x)\n'
                                         '        _finite("slider axis origin y", '
                                         'self.axis_origin_y)\n'
                                         '        _finite("slider axis angle", self.axis_angle)\n'
                                         '        _positive("connecting rod length", '
                                         'self.connecting_rod_length)\n'
                                         '        if self.assembly_branch not in (-1, 1):\n'
                                         '            raise ValueError("slider assembly_branch '
                                         'must be -1 or 1.")\n'
                                         '\n'
                                         '\n'
                                         '@dataclass(frozen=True, slots=True)\n'
                                         'class AssemblyContract:\n'
                                         '    """One complete four-bar plus slider assembly."""\n'
                                         '\n'
                                         '    loop: FourBarLoopContract\n'
                                         '    output: OutputPointContract\n'
                                         '    slider: SliderConstraintContract\n'
                                         '\n'
                                         '\n'
                                         '@dataclass(frozen=True, slots=True)\n'
                                         'class SharedCrankFourBarContract:\n'
                                         '    """Mechanical result directly mappable to the solver '
                                         'four-bar backend."""\n'
                                         '\n'
                                         '    schema_version: int\n'
                                         '    crank_radius: float\n'
                                         '    small_assembly: AssemblyContract\n'
                                         '    large_assembly: AssemblyContract\n'
                                         '    small_volume_increases_with_coordinate: bool = True\n'
                                         '    large_volume_increases_with_coordinate: bool = True\n'
                                         '    crank_angle_offset: float = 0.0\n'
                                         '    crank_direction: int = 1\n'
                                         '\n'
                                         '    def __post_init__(self) -> None:\n'
                                         '        if self.schema_version != 1:\n'
                                         '            raise ValueError("Only schema_version=1 is '
                                         'supported.")\n'
                                         '        _positive("crank radius", self.crank_radius)\n'
                                         '        _finite("crank angle offset", '
                                         'self.crank_angle_offset)\n'
                                         '        if self.crank_direction not in (-1, 1):\n'
                                         '            raise ValueError("crank_direction must be -1 '
                                         'or 1.")\n'
                                         '\n'
                                         '    def to_dict(self) -> dict[str, object]:\n'
                                         '        return asdict(self)\n',
 'src/dada_4bar_synthesis/io.py': '"""Read target laws using dada-engine-solver\'s current TOML '
                                  'conventions."""\n'
                                  '\n'
                                  'from __future__ import annotations\n'
                                  '\n'
                                  'from pathlib import Path\n'
                                  'import tomllib\n'
                                  '\n'
                                  'from .contracts import FreeKinematicsTarget, FreeMotionTarget\n'
                                  '\n'
                                  '\n'
                                  'def load_solver_free_kinematics_target(\n'
                                  '    path: str | Path,\n'
                                  ') -> FreeKinematicsTarget:\n'
                                  '    """Load a free target from a normal dada-engine-solver TOML '
                                  'file.\n'
                                  '\n'
                                  '    Reads the same source fields used by\n'
                                  '    dada_solver.configuration._load_free_kinematics().\n'
                                  '    No motor-direction or phase transformation is performed '
                                  'here.\n'
                                  '    """\n'
                                  '\n'
                                  '    path = Path(path)\n'
                                  '    with path.open("rb") as stream:\n'
                                  '        data = tomllib.load(stream)\n'
                                  '\n'
                                  '    try:\n'
                                  '        geometry = data["geometry"]\n'
                                  '        kinematics = data["kinematics"]\n'
                                  '    except KeyError as error:\n'
                                  '        raise ValueError(\n'
                                  '            f"Missing required solver configuration section: '
                                  '{error.args[0]}"\n'
                                  '        ) from error\n'
                                  '\n'
                                  '    if kinematics.get("type") != "free":\n'
                                  '        raise ValueError(\n'
                                  '            "dada-4bar-synthesis initially accepts only "\n'
                                  '            "[kinematics] type = \'free\'."\n'
                                  '        )\n'
                                  '\n'
                                  '    def motion(side: str) -> FreeMotionTarget:\n'
                                  '        try:\n'
                                  '            definition = kinematics[side]\n'
                                  '            controls = tuple(float(v) for v in '
                                  'definition["control_values"])\n'
                                  '            minimum = '
                                  'float(geometry[f"{side}_cylinder_minimum_volume"])\n'
                                  '            maximum = '
                                  'float(geometry[f"{side}_cylinder_maximum_volume"])\n'
                                  '        except KeyError as error:\n'
                                  '            raise ValueError(\n'
                                  '                f"Missing required solver configuration field: '
                                  '{error.args[0]}"\n'
                                  '            ) from error\n'
                                  '\n'
                                  '        first = '
                                  'definition.get("maximum_absolute_first_derivative")\n'
                                  '        second = '
                                  'definition.get("maximum_absolute_second_derivative")\n'
                                  '\n'
                                  '        return FreeMotionTarget(\n'
                                  '            control_values=controls,\n'
                                  '            minimum_volume=minimum,\n'
                                  '            maximum_volume=maximum,\n'
                                  '            maximum_absolute_first_derivative=(\n'
                                  '                None if first is None else float(first)\n'
                                  '            ),\n'
                                  '            maximum_absolute_second_derivative=(\n'
                                  '                None if second is None else float(second)\n'
                                  '            ),\n'
                                  '        )\n'
                                  '\n'
                                  '    return FreeKinematicsTarget(\n'
                                  '        small=motion("small"),\n'
                                  '        large=motion("large"),\n'
                                  '    )\n',
 'docs/IO_CONTRACT.md': '# I/O contract with dada-engine-solver\n'
                        '\n'
                        '## Principle\n'
                        '\n'
                        '`dada-engine-solver` remains the reference implementation for '
                        'thermodynamics,\n'
                        '`FreeKinematics`, and physical four-bar evaluation.\n'
                        '\n'
                        '`dada-4bar-synthesis` is responsible only for inverse kinematic '
                        'synthesis.\n'
                        '\n'
                        '## Input: target law\n'
                        '\n'
                        'The initial input is a standard solver TOML containing:\n'
                        '\n'
                        '```toml\n'
                        '[geometry]\n'
                        'small_cylinder_minimum_volume = ...\n'
                        'small_cylinder_maximum_volume = ...\n'
                        'large_cylinder_minimum_volume = ...\n'
                        'large_cylinder_maximum_volume = ...\n'
                        '\n'
                        '[kinematics]\n'
                        'type = "free"\n'
                        '\n'
                        '[kinematics.small]\n'
                        'control_values = [...]\n'
                        '\n'
                        '[kinematics.large]\n'
                        'control_values = [...]\n'
                        '```\n'
                        '\n'
                        'Optional derivative limits use exactly the solver names:\n'
                        '\n'
                        '```toml\n'
                        'maximum_absolute_first_derivative = ...\n'
                        'maximum_absolute_second_derivative = ...\n'
                        '```\n'
                        '\n'
                        'The angle convention is the `FreeKinematics` study-angle convention:\n'
                        'theta in radians, period `2*pi`, with no implicit motor reversal.\n'
                        '\n'
                        '## Output: realizable mechanism\n'
                        '\n'
                        'The result maps one-to-one onto the low-level backend already present in\n'
                        '`dada-engine-solver`.\n'
                        '\n'
                        '`loop` maps to `FourBarLoop`:\n'
                        '- `coupler_length`\n'
                        '- `rocker_length`\n'
                        '- `rocker_pivot_x`\n'
                        '- `rocker_pivot_y`\n'
                        '- `assembly_branch`\n'
                        '\n'
                        '`output` maps to either `RockerOutputPoint` or `CouplerOutputPoint`:\n'
                        '- `type = "rocker" | "coupler"`\n'
                        '- `along`\n'
                        '- `normal`\n'
                        '\n'
                        '`slider` maps to `SliderConstraint`:\n'
                        '- `axis_origin_x`\n'
                        '- `axis_origin_y`\n'
                        '- `axis_angle`\n'
                        '- `connecting_rod_length`\n'
                        '- `assembly_branch`\n'
                        '\n'
                        'The shared result also contains:\n'
                        '- `crank_radius`\n'
                        '- `crank_angle_offset`\n'
                        '- `crank_direction`\n'
                        '- `small_volume_increases_with_coordinate`\n'
                        '- `large_volume_increases_with_coordinate`\n'
                        '\n'
                        '## Why not SharedCrankRockerDesign?\n'
                        '\n'
                        'That convenience design is currently narrower than the underlying '
                        'backend:\n'
                        'it always constructs a rocker output and fixes `axis_angle=0`.\n'
                        '\n'
                        'The synthesis result therefore targets the lower-level classes, which '
                        'already\n'
                        'support coupler points and arbitrary slider-axis angles.\n'
                        '\n'
                        'This should require only a small adapter in `dada-engine-solver`, not a '
                        'new\n'
                        'four-bar implementation.\n'
                        '\n'
                        '## Versioning\n'
                        '\n'
                        'The output contract starts at `schema_version = 1`.\n',
 'tests/test_io_contract.py': 'import math\n'
                              '\n'
                              'import pytest\n'
                              '\n'
                              'from dada_4bar_synthesis.contracts import (\n'
                              '    AssemblyContract,\n'
                              '    FourBarLoopContract,\n'
                              '    OutputPointContract,\n'
                              '    SharedCrankFourBarContract,\n'
                              '    SliderConstraintContract,\n'
                              ')\n'
                              'from dada_4bar_synthesis.io import '
                              'load_solver_free_kinematics_target\n'
                              '\n'
                              '\n'
                              'def test_loads_current_solver_free_kinematics_format(tmp_path):\n'
                              '    path = tmp_path / "solver.toml"\n'
                              '    path.write_text(\n'
                              '        """\n'
                              '[geometry]\n'
                              'small_cylinder_minimum_volume = 1.0e-5\n'
                              'small_cylinder_maximum_volume = 4.0e-5\n'
                              'large_cylinder_minimum_volume = 2.0e-5\n'
                              'large_cylinder_maximum_volume = 1.2e-4\n'
                              '\n'
                              '[kinematics]\n'
                              'type = "free"\n'
                              '\n'
                              '[kinematics.small]\n'
                              'control_values = [0.2, 0.85, 1.0, 0.6, 0.1, 0.0]\n'
                              '\n'
                              '[kinematics.large]\n'
                              'control_values = [1.0, 0.7, 0.1, 0.0, 0.3, 0.9]\n'
                              'maximum_absolute_first_derivative = 0.001\n'
                              '""",\n'
                              '        encoding="utf-8",\n'
                              '    )\n'
                              '\n'
                              '    target = load_solver_free_kinematics_target(path)\n'
                              '\n'
                              '    assert target.small.control_values == (0.2, 0.85, 1.0, 0.6, '
                              '0.1, 0.0)\n'
                              '    assert target.small.minimum_volume == pytest.approx(1.0e-5)\n'
                              '    assert target.small.maximum_volume == pytest.approx(4.0e-5)\n'
                              '    assert target.large.minimum_volume == pytest.approx(2.0e-5)\n'
                              '    assert target.large.maximum_volume == pytest.approx(1.2e-4)\n'
                              '    assert target.large.maximum_absolute_first_derivative == '
                              'pytest.approx(0.001)\n'
                              '    assert target.cycle_angle == pytest.approx(2.0 * math.pi)\n'
                              '\n'
                              '\n'
                              'def test_rejects_non_free_solver_kinematics(tmp_path):\n'
                              '    path = tmp_path / "solver.toml"\n'
                              '    path.write_text(\n'
                              '        """\n'
                              '[geometry]\n'
                              'small_cylinder_minimum_volume = 1.0e-5\n'
                              'small_cylinder_maximum_volume = 4.0e-5\n'
                              'large_cylinder_minimum_volume = 2.0e-5\n'
                              'large_cylinder_maximum_volume = 1.2e-4\n'
                              '\n'
                              '[kinematics]\n'
                              'type = "shared_crank_rocker"\n'
                              '""",\n'
                              '        encoding="utf-8",\n'
                              '    )\n'
                              '\n'
                              '    with pytest.raises(ValueError, match="type = \'free\'"):\n'
                              '        load_solver_free_kinematics_target(path)\n'
                              '\n'
                              '\n'
                              'def test_output_contract_matches_low_level_solver_concepts():\n'
                              '    assembly = AssemblyContract(\n'
                              '        loop=FourBarLoopContract(\n'
                              '            coupler_length=0.12,\n'
                              '            rocker_length=0.14,\n'
                              '            rocker_pivot_x=0.10,\n'
                              '            rocker_pivot_y=0.0,\n'
                              '            assembly_branch=1,\n'
                              '        ),\n'
                              '        output=OutputPointContract(\n'
                              '            type="coupler",\n'
                              '            along=0.09,\n'
                              '            normal=-0.04,\n'
                              '        ),\n'
                              '        slider=SliderConstraintContract(\n'
                              '            axis_origin_x=0.0,\n'
                              '            axis_origin_y=-0.02,\n'
                              '            axis_angle=0.37,\n'
                              '            connecting_rod_length=0.30,\n'
                              '            assembly_branch=1,\n'
                              '        ),\n'
                              '    )\n'
                              '\n'
                              '    result = SharedCrankFourBarContract(\n'
                              '        schema_version=1,\n'
                              '        crank_radius=0.045,\n'
                              '        small_assembly=assembly,\n'
                              '        large_assembly=assembly,\n'
                              '        crank_angle_offset=0.2,\n'
                              '        crank_direction=-1,\n'
                              '    )\n'
                              '\n'
                              '    raw = result.to_dict()\n'
                              '    assert raw["schema_version"] == 1\n'
                              '    assert raw["small_assembly"]["output"]["type"] == "coupler"\n'
                              '    assert raw["small_assembly"]["slider"]["axis_angle"] == '
                              'pytest.approx(0.37)\n'
                              '    assert raw["crank_direction"] == -1\n'}

for name, content in FILES.items():
    path = Path(name)
    path.parent.mkdir(parents=True, exist_ok=True)
    if path.exists():
        raise SystemExit(f"Refusing to overwrite existing file: {path}")
    path.write_text(content, encoding="utf-8")
    print(f"created {path}")

print("\nNext:")
print("  python -m pip install -e '.[test]'")
print("  pytest")
